"""
=============================================================================
IDRO-AI Prediction Test Script (predict_test.py)
=============================================================================

1. HOW TO RUN:
   - Open terminal or command prompt.
   - Navigate to the project folder: cd "d:\IDRO\IDRO-AI"
   - Run the command: python predict_test.py

2. REQUIRED FILES:
   - 'idro_requirement_model.pkl' (Generated by train_model.py)
   - 'all_label_encoders.pkl'     (Generated by train_model.py)
   - If missing, run 'python train_model.py' first.

3. EXPECTED OUTPUT:
   - "IDRO AI Prediction Test Started" message.
   - "Sample Input Data" printed.
   - A table showing "Requirement" vs "Predicted Value".
   - "Prediction completed successfully." message.

4. TROUBLESHOOTING:
   - "Model files not found": You forgot to run train_model.py.
   - "Validation Error": The sample input data has wrong types (e.g., text instead of number).
   - "Error encoding": The sample input uses a category (e.g., "Tsunami") that was not in the training data.

=============================================================================
"""

import pandas as pd
import joblib
import numpy as np
import logging
import sys
import os

# Configure warnings to avoid noisy output for this test script
import warnings
warnings.filterwarnings('ignore')

# Configure basic logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

# Define the list of target columns (Must match training)
TARGET_COLUMNS = [
    'food_packets_per_day',
    'water_liters_per_day',
    'medical_kits_required',
    'beds_required',
    'blankets_required',
    'toilets_required',
    'power_units_required',
    'ambulances_required',
    'volunteers_required'
]

FEATURE_COLUMNS = [
    'disaster_type', 
    'severity', 
    'urgency', 
    'affected_count', 
    'injured_count', 
    'missing_count',
    'latitude',
    'longitude'
]

REQUIRED_KEYS = [
    'disaster_type', 
    'severity', 
    'urgency', 
    'affected_count', 
    'injured_count', 
    'missing_count', 
    'latitude', 
    'longitude'
]

def validate_input(input_data):
    """
    Validates the input dictionary ensuring all required keys are present
    and values are of appropriate types.
    """
    logger.info("Validating input data...")
    
    # Check for missing keys
    missing_keys = [key for key in REQUIRED_KEYS if key not in input_data]
    if missing_keys:
        error_msg = f"Output validation failed: Missing required keys: {missing_keys}"
        logger.error(error_msg)
        raise ValueError(error_msg)

    # Validate numeric types
    numeric_fields = ['affected_count', 'injured_count', 'missing_count', 'latitude', 'longitude']
    for field in numeric_fields:
        if not isinstance(input_data[field], (int, float)):
             error_msg = f"Input validation failed: Field '{field}' must be a number, got {type(input_data[field])}"
             logger.error(error_msg)
             raise TypeError(error_msg)
             
    # Validate categorical types
    categorical_fields = ['disaster_type', 'severity', 'urgency']
    for field in categorical_fields:
        if not isinstance(input_data[field], str):
            error_msg = f"Input validation failed: Field '{field}' must be a string, got {type(input_data[field])}"
            logger.error(error_msg)
            raise TypeError(error_msg)

    logger.info("Input validation passed.")
    return True

def predict_requirements():
    logger.info("--- IDRO AI Prediction Test Started ---")

    try:
        # Check if model files exist before attempting to load
        model_path = 'idro_requirement_model.pkl'
        encoder_path = 'all_label_encoders.pkl'
        
        if not os.path.exists(model_path) or not os.path.exists(encoder_path):
             logger.error("Model files not found.")
             print(f"Error: Model files '{model_path}' or '{encoder_path}' missing. Please run 'train_model.py' first.")
             return

        # 1. Load trained ML model and Encoders
        logger.info("Loading model and encoders...")
        try:
            model = joblib.load(model_path)
            encoders = joblib.load(encoder_path) 
            logger.info("Model and encoders loaded successfully.")
        except Exception as e:
            logger.error(f"Failed to load model files: {e}")
            raise RuntimeError(f"Failed to load model files: {e}")

        # 2. Create sample volunteer input data
        sample_input = {
            'disaster_type': 'Flood',
            'severity': 'High',
            'urgency': 'Immediate',
            'affected_count': 500,
            'injured_count': 20,
            'missing_count': 5,
            'latitude': 26.5775,
            'longitude': 93.1711
        }
        
        logger.info(f"Sample Input Data: {sample_input}")

        # Validate Input
        try:
            validate_input(sample_input)
        except (ValueError, TypeError) as e:
            logger.error(f"Validation Error: {e}")
            print(f"Validation Error: {e}")
            return

        # 3. Convert input into dataframe
        try:
            input_df = pd.DataFrame([sample_input])
            # Ensure columns are in the correct order
            input_df = input_df[FEATURE_COLUMNS]
        except KeyError as e:
             logger.error(f"Dataframe creation error: Missing column {e}")
             raise

        # 4. Encode categorical variables correctly
        logger.info("Encoding categorical features...")
        categorical_cols = ['disaster_type', 'severity', 'urgency']
        
        for col in categorical_cols:
            if col in encoders:
                le = encoders[col]
                try:
                    # Transform input, handle unseen labels if necessary (basic implementation assumes seen)
                    input_df[col] = le.transform(input_df[col].astype(str))
                except ValueError as e:
                    logger.error(f"Error encoding {col}: {e}. Value might not be in training data.")
                    print(f"Error: Invalid value for {col}. Must be one of {list(le.classes_)}")
                    return
            else:
                logger.warning(f"No encoder found for {col}, passing raw value (may cause model error).")

        # 5. Predict camp requirements
        logger.info("Predicting requirements...")
        try:
            predictions = model.predict(input_df)
        except Exception as e:
             logger.error(f"Prediction failed: {e}")
             raise RuntimeError(f"Prediction logic failed: {e}")
        
        # Flatten predictions
        predicted_values = predictions[0]

        # 6. Print prediction output clearly
        print("\n--- Prediction Results ---")
        print(f"{'Requirement':<25} | {'Predicted Value':<15}")
        print("-" * 45)
        
        results = {}
        for i, target in enumerate(TARGET_COLUMNS):
            val = round(predicted_values[i], 2)
            results[target] = val
            print(f"{target:<25} | {val:<15}")

        print("\n--------------------------")
        logger.info("Prediction completed successfully.")

    except Exception as e:
        logger.exception("An unexpected error occurred during the prediction process.")
        print(f"\nCRITICAL ERROR: {e}")

if __name__ == "__main__":
    predict_requirements()
